---
title: "Sample size simulations"
output: 
# html_document:
#   keep_md: yes
# md_document:
#   variant: markdown_github
  github_document:
    dev: jpeg
    toc: true
    toc_depth: 1
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, 
                      fig.path='../output/figures/SimN_fig_', 
                      #fig.height = 10,
                      cache.path = '../output/cache/SimN_cache_')
knitr::opts_knit$set(root.dir=normalizePath(".."))

set.seed(3128)
```


```{r fxns, include=TRUE, message=FALSE}
require(pavo)
require(vegan)
require(RColorBrewer)

# load aesthetic functions (plot, make colors transparent)
source('R/aesthetic.R')

# load simulation and analysis functions
source('R/simfoos.R')
source('R/simanalysis.R')
source('R/pausemcl.R')

# define simulation parameters
effs <- c(0, 0.1, 0.25, 0.5, 0.75, 1, 1.5, 2, 2.5, 3)
timeseach <- 200
effsims <- rep(effs, each=timeseach)
```


# Power and sample size

## N = 100
```{r n100sim, cache=TRUE}
simN <- 100
simulatedata.n100 <- lapply(effsims,
                           function(x)
                             simdich(N=simN, sgsqsrate=0.5, multiplier=NULL, effsize=x)
)

simulatecoldist.n100 <- pausemcl(simulatedata.n100, function(x) {
  Y <- suppressWarnings(coldist(x, achro=FALSE, qcatch='Qi'))
  Y$comparison <- NA
  Y$comparison[grepl('A', Y$patch1) & grepl('A', Y$patch2)] <- 'intra.A'
  Y$comparison[grepl('B', Y$patch1) & grepl('B', Y$patch2)] <- 'intra.B'
  Y$comparison[grepl('A', Y$patch1) & grepl('B', Y$patch2)] <- 'inter'
  Y
})
```

```{r n100ana, cache=TRUE, dependson='n100sim', results='hide'}
gc(verbose=FALSE)
adonissim.n100 <- pausemcl(simulatecoldist.n100, adoniscoldist)
#adonissim.n100 <- lapply(simulatecoldist.n100, adoniscoldist)
gc(verbose=FALSE)

scd2.n100 <- lapply(simulatecoldist.n100,'[', ,1:3, drop=FALSE)
for(i in 1:length(scd2.n100)){
  attributes(scd2.n100[[i]])[
    grep('name', names(attributes(simulatecoldist.n100[[i]])), invert=TRUE, value=TRUE)] <-
    attributes(simulatecoldist.n100[[i]])[
    grep('name', names(attributes(simulatecoldist.n100[[i]])), invert=TRUE, value=TRUE)]
}
pykesim.n100 <- pausemcl(scd2.n100, function(x) jnd2xyz(x, rotate=FALSE))
pykelm.n100 <- pausemcl(pykesim.n100, function(x) lm(as.matrix(x) ~ rep(c('gA','gB'), each=simN)))
pykemanova.n100 <- pausemcl(pykelm.n100, function(x) summary(manova(x)))
```


## N = 20
```{r n20sim, cache=TRUE}
simN <- 20
simulatedata.n20 <- lapply(effsims,
                           function(x)
                             simdich(N=simN, sgsqsrate=0.5, multiplier=NULL, effsize=x)
)
simulatedata.n20 <- lapply(simulatedata.n20, 'attr<-', which='resrefs', value=rfs)

simulatecoldist.n20 <- pausemcl(simulatedata.n20, function(x) {
  Y <- suppressWarnings(coldist(x, achro=FALSE, qcatch='Qi'))
  Y$comparison <- NA
  Y$comparison[grepl('A', Y$patch1) & grepl('A', Y$patch2)] <- 'intra.A'
  Y$comparison[grepl('B', Y$patch1) & grepl('B', Y$patch2)] <- 'intra.B'
  Y$comparison[grepl('A', Y$patch1) & grepl('B', Y$patch2)] <- 'inter'
  Y
})
```

```{r n20ana, cache=TRUE, dependson='n20sim', results='hide'}
gc(verbose=FALSE)
adonissim.n20 <- pausemcl(simulatecoldist.n20, adoniscoldist)
Sys.sleep(5)
gc(verbose=FALSE)

scd2.n20 <- lapply(simulatecoldist.n20,'[', ,1:3, drop=FALSE)
for(i in 1:length(scd2.n20)){
  attributes(scd2.n20[[i]])[
    grep('name', names(attributes(simulatecoldist.n20[[i]])), invert=TRUE, value=TRUE)] <-
    attributes(simulatecoldist.n20[[i]])[
    grep('name', names(attributes(simulatecoldist.n20[[i]])), invert=TRUE, value=TRUE)]
}
pykesim.n20 <- lapply(scd2.n20, function(x) jnd2xyz(x, rotate=FALSE))
pykelm.n20 <- lapply(pykesim.n20, function(x) lm(as.matrix(x) ~ rep(c('gA','gB'), each=simN)))
pykemanova.n20 <- lapply(pykelm.n20, function(x) summary(manova(x)))
```


## N = 10
```{r n10sim, cache=TRUE}
simN <- 10
simulatedata.n10 <- lapply(effsims,
                       function(x)
                       simdich(N=simN, sgsqsrate=0.5, multiplier=NULL, effsize=x)
                       )
simulatedata.n10 <- lapply(simulatedata.n10, 'attr<-', which='resrefs', value=rfs)

simulatecoldist.n10 <- pausemcl(simulatedata.n10, function(x) {
  Y <- suppressWarnings(coldist(x, achro=FALSE, qcatch='Qi'))
  Y$comparison <- NA
  Y$comparison[grepl('A', Y$patch1) & grepl('A', Y$patch2)] <- 'intra.A'
  Y$comparison[grepl('B', Y$patch1) & grepl('B', Y$patch2)] <- 'intra.B'
  Y$comparison[grepl('A', Y$patch1) & grepl('B', Y$patch2)] <- 'inter'
  Y
  })
```

```{r n10ana, cache=TRUE, dependson='n10sim', results='hide'}
gc(verbose=FALSE)
adonissim.n10 <- pausemcl(simulatecoldist.n10, adoniscoldist)
Sys.sleep(5)
gc(verbose=FALSE)

scd2.n10 <- lapply(simulatecoldist.n10,'[', ,1:3, drop=FALSE)
for(i in 1:length(scd2.n10)){
  attributes(scd2.n10[[i]])[
    grep('name', names(attributes(simulatecoldist.n10[[i]])), invert=TRUE, value=TRUE)] <-
    attributes(simulatecoldist.n10[[i]])[
    grep('name', names(attributes(simulatecoldist.n10[[i]])), invert=TRUE, value=TRUE)]
}
pykesim.n10 <- lapply(scd2.n10, function(x) jnd2xyz(x, rotate=FALSE))
pykelm.n10 <- lapply(pykesim.n10, function(x) lm(as.matrix(x) ~ rep(c('gA','gB'), each=simN)))
pykemanova.n10 <- lapply(pykelm.n10, function(x) summary(manova(x)))
```

# Running Analysis

```{r statscalc, echo=FALSE, cache=TRUE, dependson=c('n10ana', 'n20ana', 'n100ana')}

# Recover simulations for N = 50
lsfiles <- unique(gsub('\\..*','', list.files('output/cache', full.names=TRUE)))
lazyLoad(grep('final_power_cache_poweradoniscache', lsfiles, value=TRUE))
lazyLoad(grep('final_power_cache_powerpyke', lsfiles, value=TRUE))

# Pyke MANOVA: P-values, which significant
manovaPval.n50 <- unlist(lapply(pykemanova, function(x) x$stats[1,'Pr(>F)']))
manovaP.n50 <- manovaPval.n50 < 0.05

# Adonis: P-values, which significant, R-squared
adonisPval.n50 <- unlist(lapply(adonissim, function(x) x$aov.tab$'Pr(>F)'[1]))
adonisP.n50 <- adonisPval.n50 < 0.05
adonisR2.n50 <- unlist(lapply(adonissim, function(x) x$aov.tab$'R2'[1])) * 100

# Disagreement in significance between Pyke and Adonis
disagreement.n50 <- !manovaP.n50 == adonisP.n50

# Proportion of tests significant by effect size, according to each method
pvsimsadonis.n50 <- tapply(adonisP.n50, effsims, mean)
pvsimsmanova.n50 <- tapply(manovaP.n50, effsims, mean)

# Pyke MANOVA: P-values, which significant
manovaPval.n10 <- unlist(lapply(pykemanova.n10, function(x) x$stats[1,'Pr(>F)']))
manovaPval.n20 <- unlist(lapply(pykemanova.n20, function(x) x$stats[1,'Pr(>F)']))
manovaPval.n100 <- unlist(lapply(pykemanova.n100, function(x) x$stats[1,'Pr(>F)']))
manovaP.n10 <- manovaPval.n10 < 0.05
manovaP.n20 <- manovaPval.n20 < 0.05
manovaP.n100 <- manovaPval.n100 < 0.05


# Adonis: P-values, which significant, R-squared
adonisPval.n10 <- unlist(lapply(adonissim.n10, function(x) x$aov.tab$'Pr(>F)'[1]))
adonisPval.n20 <- unlist(lapply(adonissim.n20, function(x) x$aov.tab$'Pr(>F)'[1]))
adonisPval.n100 <- unlist(lapply(adonissim.n100, function(x) x$aov.tab$'Pr(>F)'[1]))
adonisP.n10 <- adonisPval.n10 < 0.05
adonisP.n20 <- adonisPval.n20 < 0.05
adonisP.n100 <- adonisPval.n100 < 0.05
adonisR2.n10 <- unlist(lapply(adonissim.n10, function(x) x$aov.tab$'R2'[1])) * 100
adonisR2.n20 <- unlist(lapply(adonissim.n20, function(x) x$aov.tab$'R2'[1])) * 100
adonisR2.n100 <- unlist(lapply(adonissim.n100, function(x) x$aov.tab$'R2'[1])) * 100

# Disagreement in significance between Pyke and Adonis
disagreement.n10 <- !manovaP.n10 == adonisP.n10
disagreement.n20 <- !manovaP.n20 == adonisP.n20
disagreement.n100 <- !manovaP.n100 == adonisP.n100

# Proportion of tests significant by effect size, according to each method
pvsimsadonis.n10 <- tapply(adonisP.n10, effsims, mean)
pvsimsadonis.n20 <- tapply(adonisP.n20, effsims, mean)
pvsimsadonis.n100 <- tapply(adonisP.n100, effsims, mean)
pvsimsmanova.n10 <- tapply(manovaP.n10, effsims, mean)
pvsimsmanova.n20 <- tapply(manovaP.n20, effsims, mean)
pvsimsmanova.n100 <- tapply(manovaP.n100, effsims, mean)
```


## Visualizing Results

```{r, echo=FALSE, dependson='statscalc'}
powerpal <- brewer.pal(9,'PRGn')

plot(pvsimsadonis.n10~unique(effsims), pch=20, cex=2, type='b', ylab='Proportion of tests significant', xlab="Effect size (Mahalanobis' Distance)", ylim=c(0,1.2), col=powerpal[6])

points(pvsimsadonis.n20~ unique(effsims), pch=20, cex=2, type='b', col=powerpal[7])
points(pvsimsadonis.n50~ unique(effsims), pch=20, cex=2, type='b', col=powerpal[8])
points(pvsimsadonis.n100~ unique(effsims), pch=20, cex=2, type='b', col=powerpal[9])

abline(h=0.05, lty=3)
legend('topleft', legend=c("adonis, N=10",
                           "adonis, N=20",
                           "adonis, N=50",
                           "adonis, N=100"), 
       pch=20, pt.cex=2, lty=1, bty='n', seg.len=3,
       col=powerpal[c(6,7,8,9)])


plot(pvsimsmanova.n10~unique(effsims), pch=20, cex=2, type='b', ylab='Proportion of tests significant', xlab="Effect size (Mahalanobis' Distance)", ylim=c(0,1.2), col=powerpal[4])

points(pvsimsmanova.n20~ unique(effsims), pch=20, cex=2, type='b', col=powerpal[3])
points(pvsimsmanova.n50~ unique(effsims), pch=20, cex=2, type='b', col=powerpal[2])
points(pvsimsmanova.n100~ unique(effsims), pch=20, cex=2, type='b', col=powerpal[1])

abline(h=0.05, lty=3)
legend('topleft', legend=c("Pyke & MANOVA, N=10",
                           "Pyke & MANOVA, N=20",
                           "Pyke & MANOVA, N=50",
                           "Pyke & MANOVA, N=100"), 
       pch=20, pt.cex=2, lty=1, bty='n', seg.len=3,
       col=powerpal[c(4,3,2,1)])

par(mfrow=c(2,2))
plot(pvsimsadonis.n10~unique(effsims), pch=20, cex=2, type='b', ylab='Proportion of tests significant', xlab="Effect size (Mahalanobis' Distance)", ylim=c(0,1.1), col=powerpal[9], main='N=10')
points(pvsimsmanova.n10~ unique(effsims), pch=20, cex=2, type='b', col=powerpal[1])
abline(h=0.05, lty=3)

plot(pvsimsadonis.n20~unique(effsims), pch=20, cex=2, type='b', ylab='Proportion of tests significant', xlab="Effect size (Mahalanobis' Distance)", ylim=c(0,1.1), col=powerpal[9], main='N=20')
points(pvsimsmanova.n20~ unique(effsims), pch=20, cex=2, type='b', col=powerpal[1])
abline(h=0.05, lty=3)

plot(pvsimsadonis.n50~unique(effsims), pch=20, cex=2, type='b', ylab='Proportion of tests significant', xlab="Effect size (Mahalanobis' Distance)", ylim=c(0,1.1), col=powerpal[9], main='N=50')
points(pvsimsmanova.n50~ unique(effsims), pch=20, cex=2, type='b', col=powerpal[1])
abline(h=0.05, lty=3)

plot(pvsimsadonis.n100~unique(effsims), pch=20, cex=2, type='b', ylab='Proportion of tests significant', xlab="Effect size (Mahalanobis' Distance)", ylim=c(0,1.1), col=powerpal[9], main='N=100')
points(pvsimsmanova.n100~ unique(effsims), pch=20, cex=2, type='b', col=powerpal[1])
abline(h=0.05, lty=3)
``` 

```{r, echo=FALSE, dependson='statscalc'}
# Disagreement by effect size and sample size
plot(tapply(disagreement.n10, effsims, mean)*100~unique(effsims), type='b',pch=20, col=grey(0.7), ylim=c(0,40), ylab='Disagreement between approaches (%)', xlab='Effect size (Mahalanobis distance)')
points(tapply(disagreement.n20, effsims, mean)*100~unique(effsims), type='b',pch=20, col=grey(0.5))
points(tapply(disagreement.n50, effsims, mean)*100~unique(effsims), type='b',pch=20, col=grey(0.3))
points(tapply(disagreement.n100, effsims, mean)*100~unique(effsims), type='b',pch=20, col=grey(0))
```

```{r, echo=FALSE, dependson='statscalc', fig.height=14}
par(mfrow=c(4,2))
plot(adonisPval.n10~manovaPval.n10, pch=20, col=rcbalpha(0.8, 4, 'RdBu')[c(4,1)][factor(disagreement.n10)], xlab='Pyke MANOVA P-value', ylab='adonis P-value', main='N=10')
abline(0,1)
abline(h=0.05, lty=2)
abline(v=0.05, lty=2)
hist(adonisPval.n10 - manovaPval.n10, breaks=30, main='difference in P values \nbetween the two approaches')

plot(adonisPval.n20~manovaPval.n20, pch=20, col=rcbalpha(0.8, 4, 'RdBu')[c(4,1)][factor(disagreement.n20)], xlab='Pyke MANOVA P-value', ylab='adonis P-value', main='N=20')
abline(0,1)
abline(h=0.05, lty=2)
abline(v=0.05, lty=2)
hist(adonisPval.n10 - manovaPval.n20, breaks=30, main='difference in P values \nbetween the two approaches')

plot(adonisPval.n50~manovaPval.n50, pch=20, col=rcbalpha(0.8, 4, 'RdBu')[c(4,1)][factor(disagreement.n50)], xlab='Pyke MANOVA P-value', ylab='adonis P-value', main='N=50')
abline(0,1)
abline(h=0.05, lty=2)
abline(v=0.05, lty=2)
hist(adonisPval.n50 - manovaPval.n50, breaks=30, main='difference in P values \nbetween the two approaches')

plot(adonisPval.n100~manovaPval.n100, pch=20, col=rcbalpha(0.8, 4, 'RdBu')[c(4,1)][factor(disagreement.n100)], xlab='Pyke MANOVA P-value', ylab='adonis P-value', main='N=100')
abline(0,1)
abline(h=0.05, lty=2)
abline(v=0.05, lty=2)
hist(adonisPval.n10 - manovaPval.n100, breaks=30, main='difference in P values \nbetween the two approaches')
```

```{r, echo=FALSE, dependson='statscalc'}
dis.n10 <- table(adonisP.n10, manovaP.n10)/length(adonisP.n10)
dis.n20 <- table(adonisP.n20, manovaP.n20)/length(adonisP.n20)
dis.n50 <- table(adonisP.n50, manovaP.n50)/length(adonisP.n50)
dis.n100 <- table(adonisP.n100, manovaP.n100)/length(adonisP.n100)


disbar <- rbind(
  c(dis.n10[2,1], dis.n10[1,2]),
  c(dis.n20[2,1], dis.n20[1,2]),
  c(dis.n50[2,1], dis.n50[1,2]),
  c(dis.n100[2,1], dis.n100[1,2])
)

disbar <- disbar*100

rownames(disbar) <- c('10','20','50','100')
colnames(disbar) <- c('sigAdonis','sigMANOVA')

par(mfrow=c(1,1))
barplot(t(disbar), beside=TRUE, ylab='Simulations (%)',xlab='Sample size', col=powerpal[c(9,1)], ylim=c(0,15))
box()
legend('topright', legend=c('significant in Adonis but not in MANOVA','significant in MANOVA but not in Adonis'), fill=powerpal[c(9,1)], bty='n')
```

```{r}
sessionInfo()
```

Plots for publication:

```{r, echo=FALSE}
ogoma <- par()$oma
ogmar <- par()$mar

pdf(height=4*1.3*2, width=7/3*2*1.3*2, pointsize = 12*2, file='figures/samplesize_1.pdf')

par(mfrow=c(2,2), oma=c(3,3,0,0), mar=c(2,2,1,1))
plot(pvsimsadonis.n10~unique(effsims), pch=21, cex=2,  lwd=4, type='b', ylab='', xlab='', ylim=c(0,1.2), col=powerpal[9], bg=powerpal[9], xaxt='n', yaxt='n')
points(pvsimsmanova.n10~ unique(effsims), pch=21, cex=2,  lwd=4, type='b', col=powerpal[1], bg=powerpal[1])
abline(h=0.05,  lwd=4, lty=3)
axis(1, at=c(0,1,2,3))
axis(2, at=c(0,0.5,1.0))
#text(x=3.2, y=1.1, pos=2, 'N=10', cex=1.2, font=2)
text(x=grconvertX(1.02,"npc"), y=grconvertY(0.95, "npc"), cex=1.2, pos=2, "N=10") 
text(x=grconvertX(0.05,"npc"), y=grconvertY(0.95, "npc"), cex=1.5, "A") 

#legend('topleft', 
legend(x=grconvertX(0,"npc"), y=grconvertY(0.9, "npc"),
       col=powerpal[c(9,1)], pt.bg=powerpal[c(9,1)], pch=21, lty=1, 
       legend=c('distance PERMANOVA', 'cartesian MANOVA'),
       bty='n', pt.cex=2, lwd=4, cex=0.9)

plot(pvsimsadonis.n20~unique(effsims), pch=21, cex=2,  lwd=4, type='b', ylab='', xlab='', ylim=c(0,1.2), col=powerpal[9], bg=powerpal[9], xaxt='n', yaxt='n')
points(pvsimsmanova.n20~ unique(effsims), pch=21, cex=2,  lwd=4, type='b', col=powerpal[1], bg=powerpal[1])
abline(h=0.05,  lwd=4, lty=3)
axis(1, at=c(0,1,2,3))
axis(2, at=c(0,0.5,1.0))
#text(x=3.2, y=1.1, pos=2, 'N=20', cex=1.2, font=2)
text(x=grconvertX(1.02,"npc"), y=grconvertY(0.95, "npc"), cex=1.2, pos=2, "N=20") 
text(x=grconvertX(0.05,"npc"), y=grconvertY(0.95, "npc"), cex=1.5, "B") 


plot(pvsimsadonis.n50~unique(effsims), pch=21, cex=2,  lwd=4, type='b', ylab='', xlab='', ylim=c(0,1.2), col=powerpal[9], bg=powerpal[9], xaxt='n', yaxt='n')
points(pvsimsmanova.n50~ unique(effsims), pch=21, cex=2,  lwd=4, type='b', col=powerpal[1], bg=powerpal[1])
abline(h=0.05,  lwd=4, lty=3)
axis(1, at=c(0,1,2,3))
axis(2, at=c(0,0.5,1.0))
#text(x=3.2, y=1.1, pos=2, 'N=50', cex=1.2, font=2)
text(x=grconvertX(1.02,"npc"), y=grconvertY(0.95, "npc"), cex=1.2, pos=2, "N=50") 
text(x=grconvertX(0.05,"npc"), y=grconvertY(0.95, "npc"), cex=1.5, "C") 


plot(pvsimsadonis.n100~unique(effsims), pch=21, cex=2, lwd=4, type='b', ylab='', xlab='', ylim=c(0,1.2), col=powerpal[9], bg=powerpal[9], xaxt='n', yaxt='n')
points(pvsimsmanova.n100~ unique(effsims), pch=21, cex=2, lwd=4, type='b', bg=powerpal[1], col=powerpal[1])
abline(h=0.05,  lwd=4, lty=3)
axis(1, at=c(0,1,2,3))
axis(2, at=c(0,0.5,1.0))
#text(x=3.2, y=1.1, pos=2, 'N=100', cex=1.2, font=2)
text(x=grconvertX(1.02,"npc"), y=grconvertY(0.95, "npc"), cex=1.2, pos=2, "N=100") 
text(x=grconvertX(0.05,"npc"), y=grconvertY(0.95, "npc"), cex=1.5, "D") 


mtext('Simulated effect size (Mahalanobis distance)', side = 1, outer = TRUE, line = 1)
mtext('Proportion of significant tests', side = 2, outer = TRUE, line = 1)

dev.off()

pdf(height=4*1.3*2, width=7*1.3*2, pointsize = 12*2, file='figures/samplesize_2.pdf')
par(mfrow=c(1,2))
barplot(t(disbar), beside=TRUE, ylab='Simulations (%)',xlab='Sample size', col=powerpal[c(9,1)], ylim=c(0,15), yaxt='n')
axis(2, at=c(0,3,6,9,12))
box()
text(x=grconvertX(0.05,"npc"), y=grconvertY(0.95, "npc"), cex=1.5, "A") 

#legend('topleft',
legend(x=grconvertX(0,"npc"), y=grconvertY(0.9, "npc"),
       legend=c('significant only in distance PERMANOVA','significant only in cartesian MANOVA'), pch=15, cex=0.9, pt.cex=2, col=powerpal[c(9,1)], bty='n')

plot(tapply(disagreement.n10, effsims, mean)*100~unique(effsims), type='b', pch=21, col=grey(0.8), bg=grey(0.8), ylim=c(0,30), xlim=c(0,3.8), ylab='Disagreement between approaches (%)', xlab='Simulated effect size (Mahalanobis distance)', cex=2, lwd=4, xaxt='n')
axis(1, at=c(0,1,2,3))
points(tapply(disagreement.n20, effsims, mean)*100~unique(effsims), type='b', pch=21, col=grey(0.6), bg=grey(0.6), cex=2, lwd=4)
points(tapply(disagreement.n50, effsims, mean)*100~unique(effsims), type='b', pch=21, col=grey(0.4), bg=grey(0.4), cex=2, lwd=4)
points(tapply(disagreement.n100, effsims, mean)*100~unique(effsims), type='b', pch=21, col=grey(0), bg=grey(0), cex=2, lwd=4)

text(x=3.1, y=tail(tapply(disagreement.n10, effsims, mean)*100, 1), labels='N=10', pos=4)
text(x=3.1, y=tail(tapply(disagreement.n20, effsims, mean)*100, 1), labels='N=20', pos=4)
text(x=3.1, y=tail(tapply(disagreement.n50, effsims, mean)*100, 1), labels='N=50', pos=4)
text(x=3.1, y=tail(tapply(disagreement.n100, effsims, mean)*100, 1), labels='N=100', pos=4)

text(x=grconvertX(0.05,"npc"), y=grconvertY(0.95, "npc"), cex=1.5, "B") 

dev.off()
```

