---
title: "Simulations"
output: 
  #html_document
  md_document:
    variant: markdown_github
---

```{r setup, include=FALSE}
require(pavo)
require(scatterplot3d)
require(vegan)

knitr::opts_chunk$set(echo = TRUE, 
                      fig.path='../output/figures/final/final_fig', 
                      #fig.height = 10,
                      cache.path = '../output/cache/final/final_cache_')
knitr::opts_knit$set(root.dir=normalizePath(".."))

set.seed(6210)
```


```{r}

# Make RColorBrewer colors transparent
rcbalpha <- function(alpha=1, ...){
  aa <- data.frame(t(col2rgb(RColorBrewer::brewer.pal(...), alpha=F)))/255
  #aa$alpha <- alpha
  rgb(aa, alpha=alpha)
}

# significant/not significant histogram 
yesnohist <- function(x, xlab=""){
  bq <- 0.5  
  while(length(seq(0, ceiling(max(x)),by=bq)) < 10) 
    bq <- bq/2

yes <- hist(x[adonisP], breaks=seq(0, ceiling(max(x)),by=bq), plot=F)
no <- hist(x[!adonisP], breaks=seq(0, ceiling(max(x)),by=bq), plot=F)

plot(c(0,yes$breaks), c(0,yes$counts,0), type='s',col=palette[1], lwd=5,
     ylab='Frequency', xlab=xlab,
     ylim=range(c(yes$counts,no$counts))* c(0,1.1),
     xlim=c(0, max(c(yes$breaks, no$breaks)*1.1)))
lines(c(0,no$breaks), c(0,no$counts,0), col=palette[2], type='s', lwd=5)

legend('topright', col=palette[1:2], c('significant  ','not significant  '), 
       pch=15, pt.cex=2.5, bty='n')
}


# tetrahedral plot
source('R/dichtcp.R')

# simulate two groups of data
simdich <- function(N=50, sgsqsrate=10, multiplier=c(0.95, 1.05), effsize=NULL){

  musA <- runif(4, 1e-6, 1e0) # vector of means for group A
  musA <- runif(4, 1, 10)
  sgsqs <- rexp(4, sgsqsrate) # vector of standard deviations
  
  groupA <- matrix(NA, nrow=N, ncol=4)
  groupA[,1] <- rlnorm(N, meanlog=log(musA[1]), sdlog=sgsqs[1])
  groupA[,2] <- rlnorm(N, meanlog=log(musA[2]), sdlog=sgsqs[2])
  groupA[,3] <- rlnorm(N, meanlog=log(musA[3]), sdlog=sgsqs[3])
  groupA[,4] <- rlnorm(N, meanlog=log(musA[4]), sdlog=sgsqs[4])
  
  if(is.null(effsize)){
    #musB <- musA*runif(4, .8, 1.2) # vector of means for group B
    musB <- musA * runif(4, multiplier[1], multiplier[2])
  }else{
    # effsize: difference between means in units of standard deviations
    # (mahalanobis distance, approximately)
    sds <- apply(groupA, 2, sd)
    musB <- effsize*sds/2 + musA
  }
  
  groupB <- matrix(NA, nrow=N, ncol=4)
  groupB[,1] <- rlnorm(N, meanlog=log(musB[1]), sdlog=sgsqs[1])
  groupB[,2] <- rlnorm(N, meanlog=log(musB[2]), sdlog=sgsqs[2])
  groupB[,3] <- rlnorm(N, meanlog=log(musB[3]), sdlog=sgsqs[3])
  groupB[,4] <- rlnorm(N, meanlog=log(musB[4]), sdlog=sgsqs[4])
  
  combined <- data.frame(rbind(groupA,groupB))
  
  colnames(combined) <- c('u','s','m', 'l')
  rownames(combined) <- paste(rep(c('gA','gB'), each=N),1:N, sep='')
  
  attr(combined, 'relative') <- FALSE
  
  simpars <- data.frame(rbind(musA, musB, sgsqs))
  colnames(simpars) <- c('u','s','m', 'l')
  rownames(simpars) <- c('muA','muB','ssq')
  attr(combined, 'simpar') <- simpars
  
  combined
  }

# testing
#simvals <- runif(100,0,10)
#aa <- lapply(simvals, simdich, N=50, sgsqsrate=10)
#mahd <- unlist(lapply(aa, function(x) sqrt(mahalanobis(colMeans(x[1:50,]), colMeans(x[51:100,]), cov(x[1:50,])) )) )
#plot(simvals~mahd)

# make distance matrix and run adonis
adoniscoldist <- function(x, ...){
  coldistres <- as.matrix(rbind(x[ ,c(1,2,3)], x[ ,c(2,1,3)]))
  uniquepatches <-  unique(c(coldistres[,1], coldistres[,2]))

  M <- matrix(nrow=length(uniquepatches), ncol=length(uniquepatches))

  rownames(M) <- colnames(M) <- uniquepatches

  M[coldistres[,1:2] ] <- coldistres[,3]
  M[coldistres[,2:1] ] <- coldistres[,3]

  class(M) <- 'numeric'
  M[is.na(M)] <- 0

  grouping <- gsub('[0-9]','', rownames(M))
  
  adonis(M~grouping, ...)
  }

# split data and run volume overlap
voloverlaptest <- function(dat){
  tcsdat <- suppressWarnings(colspace(dat, space='tcs'))
  gA <- tcsdat[1:(dim(dat)[1]/2),]
  gB <- tcsdat[(dim(dat)[1]/2+1):(dim(dat)[1]),]
  
  voloverlap(gA, gB)
}

# split data, get centroids, get color distance
centroidist <- function(dat){
  gA.c <- colMeans(dat[1:(dim(dat)[1]/2),])
  gB.c <- colMeans(dat[(dim(dat)[1]/2+1):(dim(dat)[1]),])
  
  suppressWarnings(coldist(rbind(gA.c, gB.c), achro=FALSE, qcatch='Qi'))$dS
}


```

## False positives and power

```{r powercoldistcache, cache=TRUE}
effs <- c(0, 0.1, 0.25, 0.5, 0.75, 1, 1.5, 2, 2.5, 3)
timeseach <- 100

effsims <- rep(effs, each=timeseach)

simulatedata <- lapply(effsims,
                       function(x)
                       simdich(N=50, sgsqsrate=10, multiplier=NULL, effsize=x)
                       )


simulatecoldist <- parallel::mclapply(simulatedata, function(x) {
  Y <- suppressWarnings(coldist(x, achro=FALSE, qcatch='Qi'))
  Y$comparison <- NA
  Y$comparison[grepl('A', Y$patch1) & grepl('A', Y$patch2)] <- 'intra.A'
  Y$comparison[grepl('B', Y$patch1) & grepl('B', Y$patch2)] <- 'intra.B'
  Y$comparison[grepl('A', Y$patch1) & grepl('B', Y$patch2)] <- 'inter'
  Y
  }, mc.cores=6)
```

Run stuff
```{r poweradoniscache, cache=TRUE, dependson='powercoldistcache'}
adonissim <- parallel::mclapply(simulatecoldist, adoniscoldist, mc.cores=6)
vovsim <- parallel::mclapply(simulatedata, voloverlaptest, mc.cores=6)
centdist <- unlist(lapply(simulatedata, centroidist))
gc()
```

Plot stuff

```{r, echo=FALSE, fig.width=7, fig.height=4.5, dependson=c('powercoldistcache', 'poweradoniscache')}
adonisPval <- unlist(lapply(adonissim, function(x) x$aov.tab$'Pr(>F)'[1]))
adonisP <- adonisPval < 0.05
#adonisP <- factor(adonisP < 0.05, labels=c('no', 'yes'))
adonisR2 <- unlist(lapply(adonissim, function(x) x$aov.tab$'R2'[1])) * 100

overlap <- unlist(lapply(vovsim, '[','vboth')) * 100

gmeans <- lapply(simulatecoldist, function(x) tapply(x$dS, x$comparison, mean))
gmeans <- do.call(rbind, gmeans)

intradist <- rowMeans(gmeans[, -1])
interdist <- gmeans[,"inter"]

centroidP <- centdist > 1

palette <- rcbalpha(0.8, 3, 'Set1')

sigpal <- as.character(factor(adonisP, labels=palette[1:2]))
sigpal <- as.character(factor(paste(adonisP, centroidP), labels=rcbalpha(0.8, 6, 'RdBu')[c(3,1,6,4)] ))

h1 <- hist(interdist, breaks=seq(0, ceiling(max(interdist)),by=0.5), plot=F)
h2 <- hist(intradist, breaks=seq(0, ceiling(max(intradist)),by=0.5), plot=F)
h3 <- hist(centdist, breaks=seq(0, ceiling(max(centdist)),by=0.5), plot=F)

par(mar=c(4,4.5,1.5,1.5))

plot(c(0,h1$breaks), c(0,h1$counts,0), type='s',col=palette[1], lwd=5,
     ylab='Frequency', xlab='mean distance (JND)',
     ylim=range(c(h1$counts,h2$counts,h3$counts))* c(0,1.1))
lines(c(0,h2$breaks), c(0,h2$counts,0), col=palette[2], type='s', lwd=5)
lines(c(0,h3$breaks), c(0,h3$counts,0), col=palette[3], type='s', lwd=5)

legend('topright', col=palette, c('between-group  ','within-group', 'centroid'), 
       pch=15, pt.cex=2.5, bty='n')
```
  
color legend:

* dark colors: methods disagree (BAD)
* light colors: methods agree (GOOD)
  
* light blue: adonis and centroid distance > 1 (GOOD)
* dark blue: adonis significant, centroid distance < 1 (BAD)
* dark red: adonis non-significant, centroid distance > 1 (BAD)
* light red: adonis and centroid distance < 1 (GOOD)
```{r, echo=FALSE, fig.width=7, fig.height=7, dependson=c('powercoldistcache', 'poweradoniscache')}

pvsims <- tapply(adonisP, effsims, mean)
plot(pvsims~unique(effsims), pch=20, type='b', ylab='Proportion tests significant', xlab="Effect size (Mahalanobis' Distance)", ylim=c(0,1))
abline(h=0.05, lty=2)

plot(tapply(adonisR2, effsims, mean)~unique(effsims), pch=20, type='b', ylab='R2 from adonis', xlab="Effect size (Mahalanobis' Distance)", ylim=c(0,40))
segments(unique(effsims), tapply(adonisR2, effsims, quantile, 0.025), unique(effsims), tapply(adonisR2, effsims, quantile, 0.975))

plot(tapply(centdist, effsims, mean)~unique(effsims), pch=20, ylab='Centroid distance', xlab="Effect size (Mahalanobis' Distance)", log='y', ylim=c(1e-1,60))
abline(h=1, lty=2)
segments(unique(effsims), tapply(centdist, effsims, quantile, 0.025), unique(effsims), tapply(centdist, effsims, quantile, 0.975))
```

```{r}
sessionInfo()
```
