---
title: "Example, using data on Sri-Lankan Horned Lizards"
output:
  md_document:
    variant: markdown_github

---

```{r setup, include=FALSE}
require(pavo)
require(scatterplot3d)
require(ggplot2)
require(gridExtra)

knitr::opts_chunk$set(echo = TRUE, 
                      fig.path='output/figures/lizardeg/lizardeg_fig')
```

# Example w/ real data 

### Reflectance data from several body regions of male and female _Ctenophorus ornatus_ (Whiting et al. 2015, Biol J Linn Soc)

Calculate deltaS

```{r}

specs <- list(lab = as.rspec(read.csv('data/lab.csv'), interp = FALSE),
              throat = as.rspec(read.csv('data/throat.csv'), interp = FALSE),
              roof = as.rspec(read.csv('data/roof.csv'), interp = FALSE),
              tongue = as.rspec(read.csv('data/tongue.csv'), interp = FALSE))

# Ctenophorus ornatus
liz_vis <- sensmodel(c(360, 440, 493, 571)) 
names(liz_vis) <- c('wl', 'u', 's', 'm', 'l')

models <- lapply(specs, function(x) vismodel(x, visual = liz_vis, relative = FALSE, qcatch = "fi", scale = 10000))

deltaS <- lapply(models, function(x) coldist(x, achro = FALSE, n1 = 1, n2 = 1, n3 = 3.5, n4 = 6, v = 0.10))

# To add group labels
comp_lab <- function(x){
  x$comparison[grepl('F', x$patch1) & grepl('F', x$patch2)] <- 'intra.F'
  x$comparison[grepl('M', x$patch1) & grepl('M', x$patch2)] <- 'intra.M'
  x$comparison[grepl('M', x$patch1) & grepl('F', x$patch2)] <- 'inter'
  x$comparison[grepl('F', x$patch1) & grepl('M', x$patch2)] <- 'inter'
  x
}

deltaS$lab <- comp_lab(deltaS$lab) 
deltaS$throat <- comp_lab(deltaS$throat)
deltaS$roof <- comp_lab(deltaS$roof)
deltaS$tongue <- comp_lab(deltaS$tongue)


```

Plot 'em

```{r}
# Check 'em out
p1 <- ggplot(deltaS$lab, aes(x=dS, fill=comparison)) + geom_histogram(bins=50) + 
        facet_grid(comparison~., scales='free_y') + geom_vline(xintercept=1) +
        ggtitle('labial') + theme(legend.position="none")

p2 <- ggplot(deltaS$throat, aes(x=dS, fill=comparison)) + geom_histogram(bins=50) + 
        facet_grid(comparison~., scales='free_y') + geom_vline(xintercept=1) +
        ggtitle('throat') + theme(legend.position="none")

p3 <- ggplot(deltaS$roof, aes(x=dS, fill=comparison)) + geom_histogram(bins=50) + 
        facet_grid(comparison~., scales='free_y') + geom_vline(xintercept=1) +
        ggtitle('roof') + theme(legend.position="none")

p4 <- ggplot(deltaS$tongue, aes(x=dS, fill=comparison)) + geom_histogram(bins=50) + 
        facet_grid(comparison~., scales='free_y') + geom_vline(xintercept=1) +
        ggtitle('tongue') + theme(legend.position="none")

grid.arrange(p1, p2, p3, p4, ncol=2)

```


```{r}
sessionInfo()
```
